### ISSUE TITLE
Making VPro best plugin on the world

### ISSUE THREAD

**Issue by notFallingDevil** [VolmitSoftware/VehiclesPlus#75]
1. Add way to turn on/off the engine
2. Add car keys so anyone with the keys can open/close the car and turn on/off the engine
3. Learn some complicated maths and add vehicles colissions (car to car collision)
4. Add an option to add vehicles break like for example: cars health 85-100 the car has normal model, 60-84 the car model is a little broke, 30-59 car is medium broke, etc. just add that for ecample i can make each car 5 models, that will represent car health and the models will change while we gain or loose health
5. Remove that the car blows up when health is equal 0, make it just stop and add an option for vp.mechanic guys to fix stopped cars
6. Make exactly the same gui tuning that was in vpro1
7. Add police/medic sirens option to add to a car
8. Add fuel pumps like in vpro1
9. Make brakes stop the car a little bit faster
10. Make wheels rotate (simply rotate armor stand with wheel like you know)
11. Add car radio so while in car, if engine is on and u click on the radio (u can change X Y Z in config) you open gui with every minecraft music on CD and you can play one of them so everyone in the car hears it.
12. Add seatbelts and crash effect so basicly on crash with wall/another car we get damage and our screen gets black out for some time but if we got seatbelts the crash effect is much much "easier" u know and also while being seatbelted u can't get out from the car.
13. I will edit later

**Comment by stijnb1234** [comment]
1. How do you mean the engine?
2. You are welcome to create an Addon for this. I do not think its something the main plugin should include.
3. Already included
4. -
5. Possible with API. Option for this is on todo list.
6. Screens of that? We do not have the source of vp1.
7. Possible with API. Acceleration is related to break force.
8. On todo list atm
9. Possible with API. More something for an extension. 
10. Thought that was already included. 🤔 Should be possible.
11. More something for an API. Also very difficult because the vehicle is moving and sound has an fixed position.
12. Sound like something for an extension.

**Comment by relavis** [comment]
Please follow the issue format and create an issue for each suggestion.
